### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by adamretter** [comment]
@joewiz @duncdrum Bing Bong! Any motion on this please?

**Comment by joewiz** [comment]
@adamretter A clean clone of the master branch builds just fine for me, without the fixes in this PR. Can you elaborate on the error you get that this PR fixes?

```
$ git clone git://github.com/eXist-db/shared-resources.git
Cloning into 'shared-resources'...
remote: Counting objects: 514, done.
remote: Total 514 (delta 0), reused 0 (delta 0), pack-reused 514
Receiving objects: 100% (514/514), 619.49 KiB | 2.74 MiB/s, done.
Resolving deltas: 100% (223/223), done.

$ cd shared-resources/

$ git submodule update --init --recursive
Submodule 'support/ace' (git://github.com/ajaxorg/ace.git) registered for path 'support/ace'
Cloning into '/Users/joe/workspace/shared-resources/support/ace'...
Submodule path 'support/ace': checked out 'fdbd11d3dfa758761dfbc28b49d9eb8a1831f246'
Submodule 'build' (git://github.com/ajaxorg/ace-builds.git) registered for path 'support/ace/build'
Submodule 'doc/wiki' (git://github.com/ajaxorg/ace.wiki.git) registered for path 'support/ace/doc/wiki'
Cloning into '/Users/joe/workspace/shared-resources/support/ace/build'...
Cloning into '/Users/joe/workspace/shared-resources/support/ace/doc/wiki'...
Submodule path 'support/ace/build': checked out 'fc9d2cae9fe8e6e95e74c86a31d21caadd8f9f39'
Submodule path 'support/ace/doc/wiki': checked out 'd93670b47d776987b38bb2c31777c4e488338fac'

$ ant
Buildfile: /Users/joe/workspace/shared-resources/build.xml

prepare-ace:
      [get] Getting: https://nightwing.github.io/emmet-core/emmet.js
      [get] To: /Users/joe/workspace/shared-resources/resources/scripts/emmet.js

ace:
    [mkdir] Created dir: /Users/joe/workspace/shared-resources/resources/scripts/ace
     [copy] Copying 285 files to /Users/joe/workspace/shared-resources/resources/scripts/ace

xar:
    [mkdir] Created dir: /Users/joe/workspace/shared-resources/build
     [copy] Copying 1 file to /Users/joe/workspace/shared-resources
      [zip] Building zip: /Users/joe/workspace/shared-resources/build/shared-resources-0.4.2.xar

all:

BUILD SUCCESSFUL
Total time: 2 seconds
```

**Comment by adamretter** [comment]
@joewiz Well...

1. The `import modules` are just improvements in XQuery style.
2. On a clean checkout I could not get it to build without having the `build.xml` create those directories.

**Comment by joewiz** [comment]
@adamretter I'm sure you've moved on from this issue, but is there any chance you could paste in your terminal input showing the error? Since I'm not seeing any problem, it would be helpful to see the error output.

**Comment by adamretter** [comment]
@joewiz sure here it is:

```
ant
Buildfile: /private/tmp/shared-resources/build.xml

prepare-ace:
      [get] Getting: https://nightwing.github.io/emmet-core/emmet.js
      [get] To: /private/tmp/shared-resources/resources/scripts/emmet.js

ace:
    [mkdir] Created dir: /private/tmp/shared-resources/resources/scripts/ace

BUILD FAILED
/private/tmp/shared-resources/build.xml:22: /private/tmp/shared-resources/support/ace/build/src-min does not exist.
```

**Pull request merged**
